### ISSUE TITLE
Multiprocessing BrokenPipe error

### ISSUE THREAD

**Issue by legaultmarc** [pgxcentre/genetest#9]

**Comment by rochefca** [comment]
Running with the option "cpus" set to a number of processors greater than the actual number of available processors raised a broken pipe error (see traceback below).

Traceback (most recent call last):
  File "/usr/lib64/python3.5/multiprocessing/queues.py", line 247, in _feed
    send_bytes(obj)
  File "/usr/lib64/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
